name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    outputs:
      image-tag: ${{ steps.meta.outputs.image_tag }}
      image-uri: ${{ steps.meta.outputs.image_uri }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image metadata
        id: meta
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_uri=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: .
        run: |
          docker build -t $ECR_REPOSITORY:${{ steps.meta.outputs.image_tag }} .

      - name: Tag Docker image for ECR
        run: |
          docker tag $ECR_REPOSITORY:${{ steps.meta.outputs.image_tag }} \
            ${{ steps.meta.outputs.image_uri }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.meta.outputs.image_uri }}

      - name: Show pushed image
        run: |
          echo "Pushed image: ${{ steps.meta.outputs.image_uri }}"
